import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
    {
      name: 'Free',
      slug: 'free',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
    {
      name: 'shirt',
      slug: 'shirt',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
    {
      name: 'shirt',
      slug: 'shirttt',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
  ],
}

export default data
