const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
    {
      name: 'Free',
      slug: 'free',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
    {
      name: 'shirt',
      slug: 'shirt',
      category: 'Shirts',
      image: '/images/camired.jpg',
      price: 15,
      brand: 'Generica',
      rating: 4,
      numReviews: 6,
      countInStock: 34,
      description: 'popular camiseta',
      isFeatured: true,
      banner: '/images/camired.jpg',
    },
  ],
}

export default data
